-- AthleteProfile: physical, physiology, preferences, health, per-sport metrics
ALTER TABLE "AthleteProfile"
  ADD COLUMN "heightCm" DOUBLE PRECISION,
  ADD COLUMN "weightKg" DOUBLE PRECISION,
  ADD COLUMN "bodyFatPct" DOUBLE PRECISION,
  ADD COLUMN "restingHeartRate" INTEGER,
  ADD COLUMN "hrv" INTEGER,
  ADD COLUMN "favouriteSport" TEXT,
  ADD COLUMN "leastFavouriteSport" TEXT,
  ADD COLUMN "weeklyHoursAvailable" DOUBLE PRECISION,
  ADD COLUMN "injuryHistory" TEXT,
  ADD COLUMN "ongoingIssues" TEXT,
  ADD COLUMN "chronicConditions" TEXT,
  ADD COLUMN "mobilityLimitations" TEXT,
  ADD COLUMN "tracksMenstrualCycle" BOOLEAN DEFAULT false,
  ADD COLUMN "cycleLengthDays" INTEGER,
  ADD COLUMN "lastPeriodStart" TIMESTAMP(3),
  ADD COLUMN "swimCssSecPer100" INTEGER,
  ADD COLUMN "swimStrokeCount" INTEGER,
  ADD COLUMN "swimStrokeRate" INTEGER,
  ADD COLUMN "swimComfortOpenWater" TEXT,
  ADD COLUMN "bikeLthr" INTEGER,
  ADD COLUMN "bikeMaxHr" INTEGER,
  ADD COLUMN "bikeAvgCadence" INTEGER,
  ADD COLUMN "runThresholdPaceSec" INTEGER,
  ADD COLUMN "runLthr" INTEGER,
  ADD COLUMN "runMaxHr" INTEGER,
  ADD COLUMN "runCadence" INTEGER,
  ADD COLUMN "runGroundContactMs" INTEGER,
  ADD COLUMN "runVerticalOscMm" DOUBLE PRECISION,
  ADD COLUMN "pb5kSec" INTEGER,
  ADD COLUMN "pb10kSec" INTEGER,
  ADD COLUMN "pbHalfSec" INTEGER,
  ADD COLUMN "pbMarathonSec" INTEGER;

-- CreateTable
CREATE TABLE "RaceProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "raceName" TEXT,
    "location" TEXT,
    "raceDate" TIMESTAMP(3),
    "distanceType" TEXT,
    "swimEnvironment" TEXT,
    "waterTempC" DOUBLE PRECISION,
    "wetsuitLikely" BOOLEAN,
    "swimNotes" TEXT,
    "bikeElevationGainM" INTEGER,
    "bikeCourseType" TEXT,
    "bikeTechnicality" TEXT,
    "bikeNotes" TEXT,
    "runElevationGainM" INTEGER,
    "runCourseType" TEXT,
    "runSurface" TEXT,
    "runNotes" TEXT,
    "expectedTempC" DOUBLE PRECISION,
    "expectedHumidity" INTEGER,
    "windNotes" TEXT,
    "source" TEXT NOT NULL DEFAULT 'manual',
    "confirmed" BOOLEAN NOT NULL DEFAULT false,
    "aiConfidence" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RaceProfile_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "RaceProfile_userId_key" ON "RaceProfile"("userId");
ALTER TABLE "RaceProfile" ADD CONSTRAINT "RaceProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
